// <auto-generated />
using System;
using HotellMenu.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HotellMenu.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250325091133_FixesWithSpelling")]
    partial class FixesWithSpelling
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HotellMenu.Entities.Bookings", b =>
                {
                    b.Property<int>("BookingsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingsId"));

                    b.Property<DateTime>("CheckInDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomersId")
                        .HasColumnType("int");

                    b.Property<int>("HotelRoomsId")
                        .HasColumnType("int");

                    b.Property<int>("NbrOfGuests")
                        .HasColumnType("int");

                    b.Property<DateTime>("TotalStay")
                        .HasColumnType("datetime2");

                    b.HasKey("BookingsId");

                    b.HasIndex("CustomersId");

                    b.HasIndex("HotelRoomsId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("HotellMenu.Entities.Customers", b =>
                {
                    b.Property<int>("CustomersId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomersId"));

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CustomersId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("HotellMenu.Entities.HotelRooms", b =>
                {
                    b.Property<int>("HotelRoomsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HotelRoomsId"));

                    b.Property<bool>("IsDouble")
                        .HasColumnType("bit");

                    b.Property<int>("NbrExtraBeds")
                        .HasColumnType("int");

                    b.Property<bool>("RoomAvailability")
                        .HasColumnType("bit");

                    b.Property<int>("RoomNumber")
                        .HasColumnType("int");

                    b.Property<int>("RoomSize")
                        .HasColumnType("int");

                    b.HasKey("HotelRoomsId");

                    b.ToTable("HotelRooms");
                });

            modelBuilder.Entity("HotellMenu.Entities.Bookings", b =>
                {
                    b.HasOne("HotellMenu.Entities.Customers", "Customers")
                        .WithMany("Booking")
                        .HasForeignKey("CustomersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HotellMenu.Entities.HotelRooms", "HotelRooms")
                        .WithMany("Bookings")
                        .HasForeignKey("HotelRoomsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customers");

                    b.Navigation("HotelRooms");
                });

            modelBuilder.Entity("HotellMenu.Entities.Customers", b =>
                {
                    b.Navigation("Booking");
                });

            modelBuilder.Entity("HotellMenu.Entities.HotelRooms", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
